version: '3'
services:
  desabiller-service:
    container_name: desabiller-service-${APP_VERSION}
    image: ${REPO_DOCKER}/${APP_NAME}:${APP_VERSION}
    restart: unless-stopped
    tty: true
    environment:
      TZ: "Asia/Jakarta"

      APP_PORT: ${APP_PORT}
      REPO_DOCKER: ${REPO_DOCKER}

      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SSL_MODE: ${SSL_MODE}
      IAK_API_KEY: ${IAK_API_KEY}
      IAK_MD5_KEY: ${IAK_MD5_KEY}
      IAK_PROD_URL_POSTPAID: ${IAK_PROD_URL_POSTPAID}
      IAK_PROD_URL_PREPAID: ${IAK_PROD_URL_PREPAID}
      IAK_DEV_URL_POSTPAID: ${IAK_DEV_URL_POSTPAID}
      IAK_DEV_URL_PREPAID: ${IAK_DEV_URL_PREPAID}
      IAK_USERNAME: ${IAK_USERNAME}
      TRX_PAYMENT_PENDING: ${TRX_PAYMENT_PENDING}

      APP_ENV: ${APP_ENV}

    ports:
      - "10010:${APP_PORT}"
    networks:
        - desabiller-service_network
    logging:
        driver: "json-file"
        options:
            max-size: "200m"
networks:
  desabiller-service_network:
    # external: true
    driver: bridge
